#version 430

layout(local_size_x = 1, local_size_y = 1) in;

struct parameters
{
	int y_start;
	int x_start;
	int scanline_size;
	int bytes_per_pixel;
};


layout(std430, binding = 0) buffer lay0 { float buf_in[]; };
layout(std430, binding = 1) buffer lay1 { float buf_out[]; };
layout(std430, binding = 2) buffer lay2 { parameters param; };

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i > param.max_x)
        i = param.max_x;

    buf_out[i] = buf_in[i] * param.mult;
}
